// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Valu.cpp"
#include "Valu___024root__0.cpp"
#include "Valu__main.cpp"
#include "Valu__Trace__0.cpp"
#include "Valu__ConstPool__0__Slow.cpp"
#include "Valu___024root__Slow.cpp"
#include "Valu___024root__0__Slow.cpp"
#include "Valu___024unit__Slow.cpp"
#include "Valu___024unit__0__Slow.cpp"
#include "Valu__Syms__Slow.cpp"
#include "Valu__Trace__0__Slow.cpp"
#include "Valu__TraceDecls__0__Slow.cpp"
